import { supabase } from '../lib/supabase';
import type { UserProfile, UserMatch } from '../lib/supabase';

export interface MatchFilters {
  ageRange?: [number, number];
  religion?: string;
  caste?: string;
  education?: string;
  profession?: string;
  locationCity?: string;
  locationState?: string;
  hobbies?: string[];
  interests?: string[];
}

class MatchingService {
  async getRecommendedMatches(userId: string, filters?: MatchFilters): Promise<UserMatch[]> {
    try {
      let query = supabase
        .from('user_matches')
        .select(`
          *,
          matched_user:user_profiles!matched_user_id(*)
        `)
        .eq('user_id', userId)
        .eq('status', 'pending')
        .order('compatibility_score', { ascending: false });

      const { data, error } = await query;
      if (error) throw error;

      return data || [];
    } catch (error) {
      console.error('Get recommended matches error:', error);
      throw error;
    }
  }

  async generateMatches(userId: string): Promise<UserMatch[]> {
    try {
      // Get current user profile
      const { data: userProfile, error: userError } = await supabase
        .from('user_profiles')
        .select('*')
        .eq('id', userId)
        .single();

      if (userError) throw userError;

      // Get potential matches (opposite gender, similar age range, etc.)
      const { data: potentialMatches, error: matchError } = await supabase
        .from('user_profiles')
        .select('*')
        .neq('id', userId)
        .neq('gender', userProfile.gender)
        .eq('is_active', true);

      if (matchError) throw matchError;

      // Calculate compatibility scores
      const matches: UserMatch[] = [];
      
      for (const match of potentialMatches || []) {
        const compatibilityScore = this.calculateCompatibility(userProfile, match);
        
        if (compatibilityScore >= 30) { // Minimum threshold
          const matchData = {
            user_id: userId,
            matched_user_id: match.id,
            compatibility_score: compatibilityScore,
            match_factors: this.getMatchFactors(userProfile, match),
            status: 'pending' as const,
          };

          matches.push({
            id: '', // Will be generated by database
            ...matchData,
            created_at: new Date().toISOString(),
            matched_user: match,
          });
        }
      }

      // Insert matches into database
      if (matches.length > 0) {
        const { data: insertedMatches, error: insertError } = await supabase
          .from('user_matches')
          .upsert(
            matches.map(m => ({
              user_id: m.user_id,
              matched_user_id: m.matched_user_id,
              compatibility_score: m.compatibility_score,
              match_factors: m.match_factors,
              status: m.status,
            })),
            { onConflict: 'user_id,matched_user_id' }
          )
          .select(`
            *,
            matched_user:user_profiles!matched_user_id(*)
          `);

        if (insertError) throw insertError;
        return insertedMatches || [];
      }

      return [];
    } catch (error) {
      console.error('Generate matches error:', error);
      throw error;
    }
  }

  private calculateCompatibility(user1: UserProfile, user2: UserProfile): number {
    let score = 0;
    let factors = 0;

    // Age compatibility (20 points max)
    if (user1.date_of_birth && user2.date_of_birth) {
      const age1 = this.calculateAge(user1.date_of_birth);
      const age2 = this.calculateAge(user2.date_of_birth);
      const ageDiff = Math.abs(age1 - age2);
      
      if (ageDiff <= 2) score += 20;
      else if (ageDiff <= 5) score += 15;
      else if (ageDiff <= 8) score += 10;
      else if (ageDiff <= 12) score += 5;
      
      factors++;
    }

    // Religion compatibility (15 points max)
    if (user1.religion && user2.religion) {
      if (user1.religion === user2.religion) score += 15;
      factors++;
    }

    // Caste compatibility (10 points max)
    if (user1.caste && user2.caste) {
      if (user1.caste === user2.caste) score += 10;
      factors++;
    }

    // Education compatibility (15 points max)
    if (user1.education && user2.education) {
      const educationLevels = ['high_school', 'diploma', 'bachelors', 'masters', 'phd'];
      const level1 = educationLevels.indexOf(user1.education.toLowerCase());
      const level2 = educationLevels.indexOf(user2.education.toLowerCase());
      
      if (Math.abs(level1 - level2) <= 1) score += 15;
      else if (Math.abs(level1 - level2) <= 2) score += 10;
      
      factors++;
    }

    // Location compatibility (10 points max)
    if (user1.location_city && user2.location_city) {
      if (user1.location_city === user2.location_city) score += 10;
      else if (user1.location_state === user2.location_state) score += 5;
      factors++;
    }

    // Hobbies compatibility (15 points max)
    const commonHobbies = user1.hobbies.filter(hobby => 
      user2.hobbies.includes(hobby)
    );
    score += Math.min(commonHobbies.length * 3, 15);
    factors++;

    // Interests compatibility (15 points max)
    const commonInterests = user1.interests.filter(interest => 
      user2.interests.includes(interest)
    );
    score += Math.min(commonInterests.length * 3, 15);
    factors++;

    return Math.round(score);
  }

  private getMatchFactors(user1: UserProfile, user2: UserProfile) {
    const commonHobbies = user1.hobbies.filter(hobby => 
      user2.hobbies.includes(hobby)
    );
    const commonInterests = user1.interests.filter(interest => 
      user2.interests.includes(interest)
    );

    return {
      age_compatibility: user1.date_of_birth && user2.date_of_birth ? 
        Math.abs(this.calculateAge(user1.date_of_birth) - this.calculateAge(user2.date_of_birth)) : null,
      religion_match: user1.religion === user2.religion,
      caste_match: user1.caste === user2.caste,
      location_match: user1.location_city === user2.location_city,
      common_hobbies: commonHobbies,
      common_interests: commonInterests,
    };
  }

  private calculateAge(dateOfBirth: string): number {
    const today = new Date();
    const birthDate = new Date(dateOfBirth);
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    
    return age;
  }

  async likeProfile(userId: string, matchedUserId: string) {
    try {
      // Update match status to liked
      const { error: updateError } = await supabase
        .from('user_matches')
        .update({ status: 'liked' })
        .eq('user_id', userId)
        .eq('matched_user_id', matchedUserId);

      if (updateError) throw updateError;

      // Check if it's a mutual match
      const { data: reverseMatch, error: reverseError } = await supabase
        .from('user_matches')
        .select('*')
        .eq('user_id', matchedUserId)
        .eq('matched_user_id', userId)
        .eq('status', 'liked')
        .single();

      if (!reverseError && reverseMatch) {
        // It's a mutual match! Update both records
        await supabase
          .from('user_matches')
          .update({ status: 'mutual' })
          .in('id', [reverseMatch.id]);

        await supabase
          .from('user_matches')
          .update({ status: 'mutual' })
          .eq('user_id', userId)
          .eq('matched_user_id', matchedUserId);

        // Create chat room for mutual matches
        await this.createChatRoom(userId, matchedUserId);

        // Send notifications
        await this.sendMatchNotification(userId, matchedUserId);
        await this.sendMatchNotification(matchedUserId, userId);

        return { mutual: true };
      }

      return { mutual: false };
    } catch (error) {
      console.error('Like profile error:', error);
      throw error;
    }
  }

  async dislikeProfile(userId: string, matchedUserId: string) {
    try {
      const { error } = await supabase
        .from('user_matches')
        .update({ status: 'disliked' })
        .eq('user_id', userId)
        .eq('matched_user_id', matchedUserId);

      if (error) throw error;
    } catch (error) {
      console.error('Dislike profile error:', error);
      throw error;
    }
  }

  private async createChatRoom(user1Id: string, user2Id: string) {
    try {
      const { error } = await supabase
        .from('chat_rooms')
        .insert({
          user1_id: user1Id,
          user2_id: user2Id,
          status: 'active',
        });

      if (error) throw error;
    } catch (error) {
      console.error('Create chat room error:', error);
      throw error;
    }
  }

  private async sendMatchNotification(userId: string, matchedUserId: string) {
    try {
      const { data: matchedUser } = await supabase
        .from('user_profiles')
        .select('full_name')
        .eq('id', matchedUserId)
        .single();

      await supabase
        .from('notifications')
        .insert({
          user_id: userId,
          type: 'match',
          title: 'New Mutual Match! 💕',
          message: `You and ${matchedUser?.full_name} liked each other! Start chatting now.`,
          data: { matched_user_id: matchedUserId },
        });
    } catch (error) {
      console.error('Send match notification error:', error);
    }
  }

  async searchProfiles(filters: MatchFilters): Promise<UserProfile[]> {
    try {
      let query = supabase
        .from('user_profiles')
        .select('*')
        .eq('is_active', true);

      if (filters.religion) {
        query = query.eq('religion', filters.religion);
      }

      if (filters.caste) {
        query = query.eq('caste', filters.caste);
      }

      if (filters.education) {
        query = query.eq('education', filters.education);
      }

      if (filters.profession) {
        query = query.eq('profession', filters.profession);
      }

      if (filters.locationCity) {
        query = query.eq('location_city', filters.locationCity);
      }

      if (filters.locationState) {
        query = query.eq('location_state', filters.locationState);
      }

      if (filters.hobbies && filters.hobbies.length > 0) {
        query = query.overlaps('hobbies', filters.hobbies);
      }

      if (filters.interests && filters.interests.length > 0) {
        query = query.overlaps('interests', filters.interests);
      }

      const { data, error } = await query;
      if (error) throw error;

      return data || [];
    } catch (error) {
      console.error('Search profiles error:', error);
      throw error;
    }
  }
}

export const matchingService = new MatchingService();